WhatShallWeWatch/Models/Episode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhatShallWeWatch.Models
{
    public class Episode
    {
        public int Id { get; set; }
        public int EpisodeNumber { get; set; }
        public TimeSpan RunningTime { get; set; }
        public string Title { get; set; } 
        public int SeriesId { get; set; }
        public Series Series { get; set; }
    }
}

WhatShallWeWatch/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhatShallWeWatch.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Programme> TVShows { get; set; }
    }
}

WhatShallWeWatch/Models/Programme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WhatShallWeWatch.Models;

namespace WhatShallWeWatch.Models
{
    public class Programme
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public ICollection<Genre> Genres { get; set; }
        public ICollection<Series> Series { get; set; }
    }
}

WhatShallWeWatch/Models/Series.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhatShallWeWatch.Models
{
    public class Series
    {
        public int Id { get; set; }
        public int SeriesNumber { get; set; }
        public TimeSpan NormalEpisodeLength { get; set; }
        public int ProgrammeId { get; set; }
        public Programme Programme { get; set; }
        
        public ICollection<Episode> Episodes { get; set; }
    }
}

WhatShallWeWatch/Models/TVDB/TVDBSeries.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhatShallWeWatch.Models.TVDB
{
    public class TVDBSeries
    {
        public int SeriesId { get; set; }
        public string Title { get; set; }
        public string Overview { get; set; }

        public TVDBSeries(int id, string title, string overview)
        {
            SeriesId = id;
            Title = title;
            Overview = overview;
        }

        public TVDBSeries() { }
    }
}

WhatShallWeWatch/ViewModels/SearchTVDBViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhatShallWeWatch.ViewModels
{
    public class SearchTVDBViewModel
    {
        public int Id { get; set; }
        public string SearchTitle { get; set; }
    }
}

WhatShallWeWatch/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WhatShallWeWatch.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WhatShallWeWatch/Controllers/ProgrammeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WhatShallWeWatch.DAL;
using WhatShallWeWatch.Models;
using WhatShallWeWatch.Models.TVDB;
using WhatShallWeWatch.ViewModels;

namespace WhatShallWeWatch.Controllers
{
    public class ProgrammeController : Controller
    {
        WhatShallWeWatchDBContext Db { get; set; }
        
        public ProgrammeController()
        {
            Db = new WhatShallWeWatchDBContext();
        }

        //
        // GET: /Programme/
        public ActionResult Index()
        {       
            return View(Db.Programmes);
        }

        //
        // GET: /Programme/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Programme/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Programme/Create
        [HttpPost]
        public ActionResult Create(Programme programme)
        {
            try
            {
                Db.Programmes.Add(programme);
                Db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Programme/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Programme/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Programme/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Programme/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET /Programme/SearchTVDB
        public ActionResult SearchTVDB()
        {
            return View(new SearchTVDBViewModel());
        }

        //
        // POST /Programm/SearchTVDB
        [HttpPost]
        public ActionResult SearchTVDB(SearchTVDBViewModel model)
        {
            TVDBSeriesRepo repo = new TVDBSeriesRepo();
            IEnumerable<TVDBSeries> series = repo.GetSeries(model.SearchTitle);

            return View("SearchResults", series);
        }
    }
}

WhatShallWeWatch/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WhatShallWeWatch/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WhatShallWeWatch/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WhatShallWeWatch/Views/Programme/Create.cshtml
@model WhatShallWeWatch.Models.Programme

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Programme</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhatShallWeWatch/Views/Programme/Index.cshtml
@model IEnumerable<WhatShallWeWatch.Models.Programme>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WhatShallWeWatch/Views/Programme/SearchResults.cshtml
@model IEnumerable<WhatShallWeWatch.Models.TVDB.TVDBSeries>

@{
    ViewBag.Title = "SearchResults";
}

<h2>SearchResults</h2>

<div class="column">
    <table>
        @foreach (WhatShallWeWatch.Models.TVDB.TVDBSeries series in Model)
        {
            <tr>
                <td>
                    <b>@Html.ActionLink(series.Title, "GetEpisodes", new { seriesId = series.SeriesId} )
                </td>
                <td>
                    @Html.DisplayFor(_ => series.Overview)
                </td>
            </tr>
        }
    </table>
</div>

WhatShallWeWatch/Views/Programme/SearchTVDB.cshtml
@model WhatShallWeWatch.ViewModels.SearchTVDBViewModel

@{
    ViewBag.Title = "SearchTVDB";
}

<h2>SearchTVDB</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SearchTVDBViewModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.SearchTitle, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SearchTitle)
                @Html.ValidationMessageFor(model => model.SearchTitle)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhatShallWeWatch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Programmes", "Index", "Programme")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>